// Auto Generated by '@starnexus/generate-routes'
import type { Routes } from '@starnexus/core'
import { router as githubcom } from './website/github.com/router'
import { pathInfo as githubcomRepo } from './website/github.com/paths/repo'
import { router as twittercom } from './website/twitter.com/router'
import { pathInfo as twittercomTweet } from './website/twitter.com/paths/tweet'

githubcom.paths = [
  githubcomRepo,
].sort((a, b) => (b.sequence ?? 0) - (a.sequence ?? 0))
twittercom.paths = [
  twittercomTweet,
].sort((a, b) => (b.sequence ?? 0) - (a.sequence ?? 0))

export const routes: Routes = {
  'github.com': githubcom,
  'twitter.com': twittercom,
}
